FROM mariadb

RUN sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/my.cnf

#ADD ./Conf/my.cnf /etc/mysql/my.cnf
#ADD ./Conf/my.cnf /etc/mysql/conf.d/mysqld.cnf

CMD ["mysqld"]
